package com.empresa.repository;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import java.util.Map;
import javax.transaction.Transactional;
import com.empresa.entity.lcocmpa;
import com.empresa.entity.lcocmpaPk;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ResCompraAdiciRepository extends JpaRepository<lcocmpa, lcocmpaPk> {
        @Query(value = "{call SP_Regis_Adi_Compra(:opcion,:cia,:ejercicio,:PER,:SD,:ASIENTO,:ac_codper,:ac_subdia,:ac_compro,:ac_feccom,:ac_fecdoc,:ac_fecven,:ac_tipdoc,:ac_docser,:ac_docnum,"
                        + ":ac_numdoc,:ac_tipane,:ac_codane,:ac_tipide,:ac_numide,:ac_nomane,:ac_codmon,:ac_afemn,:ac_inamn,:ac_igvmn,"
                        + ":ac_importmn,:ac_iscmn,:ac_otrmn,:ac_idemn,:ac_afeme,:ac_iname ,:ac_igvme,:ac_importme,:ac_iscme,:ac_otrme,"
                        + ":ac_ideme,:ac_numdet,:ac_fecdet,:ac_tipcamb,:ac_fecdocref,:ac_tipdocref,:ac_docserref,:ac_docnumref,:ac_feccrea,"
                        + ":ac_hracrea,:ac_usrcrea,:ac_fecact,:ac_hraact,:ac_usract,:ac_recmn,:ac_recme,:ac_codcla,:ac_secuen,:ac_cuenta,"
                        + ":ac_perrec,:ac_medpag,:ac_estado,:ac_datadi,:ac_coddet,:ac_icbpmn,:ac_icbpme,:ac_irlqmn,:ac_irlqme)}", nativeQuery = true)
        List<Map<String, Object[]>> swListarRecCmp(
                        @Param("opcion") int opcion,
                        @Param("cia") String cia,
                        @Param("ejercicio") String ejercicio,
                        @Param("PER") String PER,
                        @Param("SD") String SD,
                        @Param("ASIENTO") String ASIENTO,
                        @Param("ac_codper") String ac_codper,
                        @Param("ac_subdia") String ac_subdia,
                        @Param("ac_compro") String ac_compro,
                        @Param("ac_feccom") LocalDate ac_feccom,
                        @Param("ac_fecdoc") LocalDate ac_fecdoc,
                        @Param("ac_fecven") LocalDate ac_fecven,
                        @Param("ac_tipdoc") String ac_tipdoc,
                        @Param("ac_docser") String ac_docser,
                        @Param("ac_docnum") String ac_docnum,
                        @Param("ac_numdoc") String ac_numdoc,
                        @Param("ac_tipane") String ac_tipane,
                        @Param("ac_codane") String ac_codane,
                        @Param("ac_tipide") String ac_tipide,
                        @Param("ac_numide") String ac_numide,
                        @Param("ac_nomane") String ac_nomane,
                        @Param("ac_codmon") String ac_codmon,
                        @Param("ac_afemn") Double ac_afemn,
                        @Param("ac_inamn") Double ac_inamn,
                        @Param("ac_igvmn") Double ac_igvmn,
                        @Param("ac_importmn") Double ac_importmn,
                        @Param("ac_iscmn") Double ac_iscmn,
                        @Param("ac_otrmn") Double ac_otrmn,
                        @Param("ac_idemn") Double ac_idemn,
                        @Param("ac_afeme") Double ac_afeme,
                        @Param("ac_iname") Double ac_iname,
                        @Param("ac_igvme") Double ac_igvme,
                        @Param("ac_importme") Double ac_importme,
                        @Param("ac_iscme") Double ac_iscme,
                        @Param("ac_otrme") Double ac_otrme,
                        @Param("ac_ideme") Double ac_ideme,
                        @Param("ac_numdet") String ac_numdet,
                        @Param("ac_fecdet") LocalDate ac_fecdet,
                        @Param("ac_tipcamb") Double ac_tipcamb,
                        @Param("ac_fecdocref") LocalDate ac_fecdocref,
                        @Param("ac_tipdocref") String ac_tipdocref,
                        @Param("ac_docserref") String ac_docserref,
                        @Param("ac_docnumref") String ac_docnumref,
                        @Param("ac_feccrea") LocalDate ac_feccrea,
                        @Param("ac_hracrea") LocalTime ac_hracrea,
                        @Param("ac_usrcrea") String ac_usrcrea,
                        @Param("ac_fecact") LocalDate ac_fecact,
                        @Param("ac_hraact") LocalTime ac_hraact,
                        @Param("ac_usract") String ac_usract,
                        @Param("ac_recmn") Double ac_recmn,
                        @Param("ac_recme") Double ac_recme,
                        @Param("ac_codcla") String ac_codcla,
                        @Param("ac_secuen") String ac_secuen,
                        @Param("ac_cuenta") String ac_cuenta,
                        @Param("ac_perrec") String ac_perrec,
                        @Param("ac_medpag") String ac_medpag,
                        @Param("ac_estado") String ac_estado,
                        @Param("ac_datadi") String ac_datadi,
                        @Param("ac_coddet") String ac_coddet,
                        @Param("ac_icbpmn") Double ac_icbpmn,
                        @Param("ac_icbpme") Double ac_icbpme,
                        @Param("ac_irlqmn") Double ac_irlqmn,
                        @Param("ac_irlqme") Double ac_irlqme);

        @Query(value = "{call SP_Regis_Adi_Compra(:opcion,:cia,:ejercicio,:PER,:SD,:ASIENTO,:ac_codper,:ac_subdia,:ac_compro,:ac_feccom,:ac_fecdoc,:ac_fecven,:ac_tipdoc,:ac_docser,:ac_docnum,"
                        + ":ac_numdoc,:ac_tipane,:ac_codane,:ac_tipide,:ac_numide,:ac_nomane,:ac_codmon,:ac_afemn,:ac_inamn,:ac_igvmn,"
                        + ":ac_importmn,:ac_iscmn,:ac_otrmn,:ac_idemn,:ac_afeme,:ac_iname ,:ac_igvme,:ac_importme,:ac_iscme,:ac_otrme,"
                        + ":ac_ideme,:ac_numdet,:ac_fecdet,:ac_tipcamb,:ac_fecdocref,:ac_tipdocref,:ac_docserref,:ac_docnumref,:ac_feccrea,"
                        + ":ac_hracrea,:ac_usrcrea,:ac_fecact,:ac_hraact,:ac_usract,:ac_recmn,:ac_recme,:ac_codcla,:ac_secuen,:ac_cuenta,"
                        + ":ac_perrec,:ac_medpag,:ac_estado,:ac_datadi,:ac_coddet,:ac_icbpmn,:ac_icbpme,:ac_irlqmn,:ac_irlqme)}", nativeQuery = true)
        List<Map<String, Object[]>> swBscRecCmp(
                        @Param("opcion") int opcion,
                        @Param("cia") String cia,
                        @Param("ejercicio") String ejercicio,
                        @Param("PER") String PER,
                        @Param("SD") String SD,
                        @Param("ASIENTO") String ASIENTO,
                        @Param("ac_codper") String ac_codper,
                        @Param("ac_subdia") String ac_subdia,
                        @Param("ac_compro") String ac_compro,
                        @Param("ac_feccom") LocalDate ac_feccom,
                        @Param("ac_fecdoc") LocalDate ac_fecdoc,
                        @Param("ac_fecven") LocalDate ac_fecven,
                        @Param("ac_tipdoc") String ac_tipdoc,
                        @Param("ac_docser") String ac_docser,
                        @Param("ac_docnum") String ac_docnum,
                        @Param("ac_numdoc") String ac_numdoc,
                        @Param("ac_tipane") String ac_tipane,
                        @Param("ac_codane") String ac_codane,
                        @Param("ac_tipide") String ac_tipide,
                        @Param("ac_numide") String ac_numide,
                        @Param("ac_nomane") String ac_nomane,
                        @Param("ac_codmon") String ac_codmon,
                        @Param("ac_afemn") Double ac_afemn,
                        @Param("ac_inamn") Double ac_inamn,
                        @Param("ac_igvmn") Double ac_igvmn,
                        @Param("ac_importmn") Double ac_importmn,
                        @Param("ac_iscmn") Double ac_iscmn,
                        @Param("ac_otrmn") Double ac_otrmn,
                        @Param("ac_idemn") Double ac_idemn,
                        @Param("ac_afeme") Double ac_afeme,
                        @Param("ac_iname") Double ac_iname,
                        @Param("ac_igvme") Double ac_igvme,
                        @Param("ac_importme") Double ac_importme,
                        @Param("ac_iscme") Double ac_iscme,
                        @Param("ac_otrme") Double ac_otrme,
                        @Param("ac_ideme") Double ac_ideme,
                        @Param("ac_numdet") String ac_numdet,
                        @Param("ac_fecdet") LocalDate ac_fecdet,
                        @Param("ac_tipcamb") Double ac_tipcamb,
                        @Param("ac_fecdocref") LocalDate ac_fecdocref,
                        @Param("ac_tipdocref") String ac_tipdocref,
                        @Param("ac_docserref") String ac_docserref,
                        @Param("ac_docnumref") String ac_docnumref,
                        @Param("ac_feccrea") LocalDate ac_feccrea,
                        @Param("ac_hracrea") LocalTime ac_hracrea,
                        @Param("ac_usrcrea") String ac_usrcrea,
                        @Param("ac_fecact") LocalDate ac_fecact,
                        @Param("ac_hraact") LocalTime ac_hraact,
                        @Param("ac_usract") String ac_usract,
                        @Param("ac_recmn") Double ac_recmn,
                        @Param("ac_recme") Double ac_recme,
                        @Param("ac_codcla") String ac_codcla,
                        @Param("ac_secuen") String ac_secuen,
                        @Param("ac_cuenta") String ac_cuenta,
                        @Param("ac_perrec") String ac_perrec,
                        @Param("ac_medpag") String ac_medpag,
                        @Param("ac_estado") String ac_estado,
                        @Param("ac_datadi") String ac_datadi,
                        @Param("ac_coddet") String ac_coddet,
                        @Param("ac_icbpmn") Double ac_icbpmn,
                        @Param("ac_icbpme") Double ac_icbpme,
                        @Param("ac_irlqmn") Double ac_irlqmn,
                        @Param("ac_irlqme") Double ac_irlqme);

        @Query(value = "{call SP_Regis_Adi_Compra(:opcion,:cia,:ejercicio,:PER,:SD,:ASIENTO,:ac_codper,:ac_subdia,:ac_compro,:ac_feccom,:ac_fecdoc,:ac_fecven,:ac_tipdoc,:ac_docser,:ac_docnum,"
                        + ":ac_numdoc,:ac_tipane,:ac_codane,:ac_tipide,:ac_numide,:ac_nomane,:ac_codmon,:ac_afemn,:ac_inamn,:ac_igvmn,"
                        + ":ac_importmn,:ac_iscmn,:ac_otrmn,:ac_idemn,:ac_afeme,:ac_iname ,:ac_igvme,:ac_importme,:ac_iscme,:ac_otrme,"
                        + ":ac_ideme,:ac_numdet,:ac_fecdet,:ac_tipcamb,:ac_fecdocref,:ac_tipdocref,:ac_docserref,:ac_docnumref,:ac_feccrea,"
                        + ":ac_hracrea,:ac_usrcrea,:ac_fecact,:ac_hraact,:ac_usract,:ac_recmn,:ac_recme,:ac_codcla,:ac_secuen,:ac_cuenta,"
                        + ":ac_perrec,:ac_medpag,:ac_estado,:ac_datadi,:ac_coddet,:ac_icbpmn,:ac_icbpme,:ac_irlqmn,:ac_irlqme)}", nativeQuery = true)
        List<Map<String, Object[]>> swConRecCmp(
                        @Param("opcion") int opcion,
                        @Param("cia") String cia,
                        @Param("ejercicio") String ejercicio,
                        @Param("PER") String PER,
                        @Param("SD") String SD,
                        @Param("ASIENTO") String ASIENTO,
                        @Param("ac_codper") String ac_codper,
                        @Param("ac_subdia") String ac_subdia,
                        @Param("ac_compro") String ac_compro,
                        @Param("ac_feccom") LocalDate ac_feccom,
                        @Param("ac_fecdoc") LocalDate ac_fecdoc,
                        @Param("ac_fecven") LocalDate ac_fecven,
                        @Param("ac_tipdoc") String ac_tipdoc,
                        @Param("ac_docser") String ac_docser,
                        @Param("ac_docnum") String ac_docnum,
                        @Param("ac_numdoc") String ac_numdoc,
                        @Param("ac_tipane") String ac_tipane,
                        @Param("ac_codane") String ac_codane,
                        @Param("ac_tipide") String ac_tipide,
                        @Param("ac_numide") String ac_numide,
                        @Param("ac_nomane") String ac_nomane,
                        @Param("ac_codmon") String ac_codmon,
                        @Param("ac_afemn") Double ac_afemn,
                        @Param("ac_inamn") Double ac_inamn,
                        @Param("ac_igvmn") Double ac_igvmn,
                        @Param("ac_importmn") Double ac_importmn,
                        @Param("ac_iscmn") Double ac_iscmn,
                        @Param("ac_otrmn") Double ac_otrmn,
                        @Param("ac_idemn") Double ac_idemn,
                        @Param("ac_afeme") Double ac_afeme,
                        @Param("ac_iname") Double ac_iname,
                        @Param("ac_igvme") Double ac_igvme,
                        @Param("ac_importme") Double ac_importme,
                        @Param("ac_iscme") Double ac_iscme,
                        @Param("ac_otrme") Double ac_otrme,
                        @Param("ac_ideme") Double ac_ideme,
                        @Param("ac_numdet") String ac_numdet,
                        @Param("ac_fecdet") LocalDate ac_fecdet,
                        @Param("ac_tipcamb") Double ac_tipcamb,
                        @Param("ac_fecdocref") LocalDate ac_fecdocref,
                        @Param("ac_tipdocref") String ac_tipdocref,
                        @Param("ac_docserref") String ac_docserref,
                        @Param("ac_docnumref") String ac_docnumref,
                        @Param("ac_feccrea") LocalDate ac_feccrea,
                        @Param("ac_hracrea") LocalTime ac_hracrea,
                        @Param("ac_usrcrea") String ac_usrcrea,
                        @Param("ac_fecact") LocalDate ac_fecact,
                        @Param("ac_hraact") LocalTime ac_hraact,
                        @Param("ac_usract") String ac_usract,
                        @Param("ac_recmn") Double ac_recmn,
                        @Param("ac_recme") Double ac_recme,
                        @Param("ac_codcla") String ac_codcla,
                        @Param("ac_secuen") String ac_secuen,
                        @Param("ac_cuenta") String ac_cuenta,
                        @Param("ac_perrec") String ac_perrec,
                        @Param("ac_medpag") String ac_medpag,
                        @Param("ac_estado") String ac_estado,
                        @Param("ac_datadi") String ac_datadi,
                        @Param("ac_coddet") String ac_coddet,
                        @Param("ac_icbpmn") Double ac_icbpmn,
                        @Param("ac_icbpme") Double ac_icbpme,
                        @Param("ac_irlqmn") Double ac_irlqmn,
                        @Param("ac_irlqme") Double ac_irlqme);

        @Query(value = "{call SP_Regis_Adi_Compra(:opcion,:cia,:ejercicio,:PER,:SD,:ASIENTO,:ac_codper,:ac_subdia,:ac_compro,:ac_feccom,:ac_fecdoc,:ac_fecven,:ac_tipdoc,:ac_docser,:ac_docnum,"
                        + ":ac_numdoc,:ac_tipane,:ac_codane,:ac_tipide,:ac_numide,:ac_nomane,:ac_codmon,:ac_afemn,:ac_inamn,:ac_igvmn,"
                        + ":ac_importmn,:ac_iscmn,:ac_otrmn,:ac_idemn,:ac_afeme,:ac_iname ,:ac_igvme,:ac_importme,:ac_iscme,:ac_otrme,"
                        + ":ac_ideme,:ac_numdet,:ac_fecdet,:ac_tipcamb,:ac_fecdocref,:ac_tipdocref,:ac_docserref,:ac_docnumref,:ac_feccrea,"
                        + ":ac_hracrea,:ac_usrcrea,:ac_fecact,:ac_hraact,:ac_usract,:ac_recmn,:ac_recme,:ac_codcla,:ac_secuen,:ac_cuenta,"
                        + ":ac_perrec,:ac_medpag,:ac_estado,:ac_datadi,:ac_coddet,:ac_icbpmn,:ac_icbpme,:ac_irlqmn,:ac_irlqme)}", nativeQuery = true)
        @Transactional
        @Modifying
        void swEliRecCmp(
                        @Param("opcion") int opcion,
                        @Param("cia") String cia,
                        @Param("ejercicio") String ejercicio,
                        @Param("PER") String PER,
                        @Param("SD") String SD,
                        @Param("ASIENTO") String ASIENTO,
                        @Param("ac_codper") String ac_codper,
                        @Param("ac_subdia") String ac_subdia,
                        @Param("ac_compro") String ac_compro,
                        @Param("ac_feccom") LocalDate ac_feccom,
                        @Param("ac_fecdoc") LocalDate ac_fecdoc,
                        @Param("ac_fecven") LocalDate ac_fecven,
                        @Param("ac_tipdoc") String ac_tipdoc,
                        @Param("ac_docser") String ac_docser,
                        @Param("ac_docnum") String ac_docnum,
                        @Param("ac_numdoc") String ac_numdoc,
                        @Param("ac_tipane") String ac_tipane,
                        @Param("ac_codane") String ac_codane,
                        @Param("ac_tipide") String ac_tipide,
                        @Param("ac_numide") String ac_numide,
                        @Param("ac_nomane") String ac_nomane,
                        @Param("ac_codmon") String ac_codmon,
                        @Param("ac_afemn") Double ac_afemn,
                        @Param("ac_inamn") Double ac_inamn,
                        @Param("ac_igvmn") Double ac_igvmn,
                        @Param("ac_importmn") Double ac_importmn,
                        @Param("ac_iscmn") Double ac_iscmn,
                        @Param("ac_otrmn") Double ac_otrmn,
                        @Param("ac_idemn") Double ac_idemn,
                        @Param("ac_afeme") Double ac_afeme,
                        @Param("ac_iname") Double ac_iname,
                        @Param("ac_igvme") Double ac_igvme,
                        @Param("ac_importme") Double ac_importme,
                        @Param("ac_iscme") Double ac_iscme,
                        @Param("ac_otrme") Double ac_otrme,
                        @Param("ac_ideme") Double ac_ideme,
                        @Param("ac_numdet") String ac_numdet,
                        @Param("ac_fecdet") LocalDate ac_fecdet,
                        @Param("ac_tipcamb") Double ac_tipcamb,
                        @Param("ac_fecdocref") LocalDate ac_fecdocref,
                        @Param("ac_tipdocref") String ac_tipdocref,
                        @Param("ac_docserref") String ac_docserref,
                        @Param("ac_docnumref") String ac_docnumref,
                        @Param("ac_feccrea") LocalDate ac_feccrea,
                        @Param("ac_hracrea") LocalTime ac_hracrea,
                        @Param("ac_usrcrea") String ac_usrcrea,
                        @Param("ac_fecact") LocalDate ac_fecact,
                        @Param("ac_hraact") LocalTime ac_hraact,
                        @Param("ac_usract") String ac_usract,
                        @Param("ac_recmn") Double ac_recmn,
                        @Param("ac_recme") Double ac_recme,
                        @Param("ac_codcla") String ac_codcla,
                        @Param("ac_secuen") String ac_secuen,
                        @Param("ac_cuenta") String ac_cuenta,
                        @Param("ac_perrec") String ac_perrec,
                        @Param("ac_medpag") String ac_medpag,
                        @Param("ac_estado") String ac_estado,
                        @Param("ac_datadi") String ac_datadi,
                        @Param("ac_coddet") String ac_coddet,
                        @Param("ac_icbpmn") Double ac_icbpmn,
                        @Param("ac_icbpme") Double ac_icbpme,
                        @Param("ac_irlqmn") Double ac_irlqmn,
                        @Param("ac_irlqme") Double ac_irlqme);

        @Query(value = "{call SP_Regis_Adi_Compra(:opcion,:cia,:ejercicio,:PER,:SD,:ASIENTO,:ac_codper,:ac_subdia,:ac_compro,:ac_feccom,:ac_fecdoc,:ac_fecven,:ac_tipdoc,:ac_docser,:ac_docnum,"
                        + ":ac_numdoc,:ac_tipane,:ac_codane,:ac_tipide,:ac_numide,:ac_nomane,:ac_codmon,:ac_afemn,:ac_inamn,:ac_igvmn,"
                        + ":ac_importmn,:ac_iscmn,:ac_otrmn,:ac_idemn,:ac_afeme,:ac_iname ,:ac_igvme,:ac_importme,:ac_iscme,:ac_otrme,"
                        + ":ac_ideme,:ac_numdet,:ac_fecdet,:ac_tipcamb,:ac_fecdocref,:ac_tipdocref,:ac_docserref,:ac_docnumref,:ac_feccrea,"
                        + ":ac_hracrea,:ac_usrcrea,:ac_fecact,:ac_hraact,:ac_usract,:ac_recmn,:ac_recme,:ac_codcla,:ac_secuen,:ac_cuenta,"
                        + ":ac_perrec,:ac_medpag,:ac_estado,:ac_datadi,:ac_coddet,:ac_icbpmn,:ac_icbpme,:ac_irlqmn,:ac_irlqme)}", nativeQuery = true)
        @Transactional
        @Modifying
        void swCrearRecCmp(
                        @Param("opcion") int opcion,
                        @Param("cia") String cia,
                        @Param("ejercicio") String ejercicio,
                        @Param("PER") String PER,
                        @Param("SD") String SD,
                        @Param("ASIENTO") String ASIENTO,
                        @Param("ac_codper") String ac_codper,
                        @Param("ac_subdia") String ac_subdia,
                        @Param("ac_compro") String ac_compro,
                        @Param("ac_feccom") LocalDate ac_feccom,
                        @Param("ac_fecdoc") LocalDate ac_fecdoc,
                        @Param("ac_fecven") LocalDate ac_fecven,
                        @Param("ac_tipdoc") String ac_tipdoc,
                        @Param("ac_docser") String ac_docser,
                        @Param("ac_docnum") String ac_docnum,
                        @Param("ac_numdoc") String ac_numdoc,
                        @Param("ac_tipane") String ac_tipane,
                        @Param("ac_codane") String ac_codane,
                        @Param("ac_tipide") String ac_tipide,
                        @Param("ac_numide") String ac_numide,
                        @Param("ac_nomane") String ac_nomane,
                        @Param("ac_codmon") String ac_codmon,
                        @Param("ac_afemn") Double ac_afemn,
                        @Param("ac_inamn") Double ac_inamn,
                        @Param("ac_igvmn") Double ac_igvmn,
                        @Param("ac_importmn") Double ac_importmn,
                        @Param("ac_iscmn") Double ac_iscmn,
                        @Param("ac_otrmn") Double ac_otrmn,
                        @Param("ac_idemn") Double ac_idemn,
                        @Param("ac_afeme") Double ac_afeme,
                        @Param("ac_iname") Double ac_iname,
                        @Param("ac_igvme") Double ac_igvme,
                        @Param("ac_importme") Double ac_importme,
                        @Param("ac_iscme") Double ac_iscme,
                        @Param("ac_otrme") Double ac_otrme,
                        @Param("ac_ideme") Double ac_ideme,
                        @Param("ac_numdet") String ac_numdet,
                        @Param("ac_fecdet") LocalDate ac_fecdet,
                        @Param("ac_tipcamb") Double ac_tipcamb,
                        @Param("ac_fecdocref") LocalDate ac_fecdocref,
                        @Param("ac_tipdocref") String ac_tipdocref,
                        @Param("ac_docserref") String ac_docserref,
                        @Param("ac_docnumref") String ac_docnumref,
                        @Param("ac_feccrea") LocalDate ac_feccrea,
                        @Param("ac_hracrea") LocalTime ac_hracrea,
                        @Param("ac_usrcrea") String ac_usrcrea,
                        @Param("ac_fecact") LocalDate ac_fecact,
                        @Param("ac_hraact") LocalTime ac_hraact,
                        @Param("ac_usract") String ac_usract,
                        @Param("ac_recmn") Double ac_recmn,
                        @Param("ac_recme") Double ac_recme,
                        @Param("ac_codcla") String ac_codcla,
                        @Param("ac_secuen") String ac_secuen,
                        @Param("ac_cuenta") String ac_cuenta,
                        @Param("ac_perrec") String ac_perrec,
                        @Param("ac_medpag") String ac_medpag,
                        @Param("ac_estado") String ac_estado,
                        @Param("ac_datadi") String ac_datadi,
                        @Param("ac_coddet") String ac_coddet,
                        @Param("ac_icbpmn") Double ac_icbpmn,
                        @Param("ac_icbpme") Double ac_icbpme,
                        @Param("ac_irlqmn") Double ac_irlqmn,
                        @Param("ac_irlqme") Double ac_irlqme);

        @Query(value = "{call SP_Regis_Adi_Compra(:opcion,:cia,:ejercicio,:PER,:SD,:ASIENTO,:ac_codper,:ac_subdia,:ac_compro,:ac_feccom,:ac_fecdoc,:ac_fecven,:ac_tipdoc,:ac_docser,:ac_docnum,"
                        + ":ac_numdoc,:ac_tipane,:ac_codane,:ac_tipide,:ac_numide,:ac_nomane,:ac_codmon,:ac_afemn,:ac_inamn,:ac_igvmn,"
                        + ":ac_importmn,:ac_iscmn,:ac_otrmn,:ac_idemn,:ac_afeme,:ac_iname ,:ac_igvme,:ac_importme,:ac_iscme,:ac_otrme,"
                        + ":ac_ideme,:ac_numdet,:ac_fecdet,:ac_tipcamb,:ac_fecdocref,:ac_tipdocref,:ac_docserref,:ac_docnumref,:ac_feccrea,"
                        + ":ac_hracrea,:ac_usrcrea,:ac_fecact,:ac_hraact,:ac_usract,:ac_recmn,:ac_recme,:ac_codcla,:ac_secuen,:ac_cuenta,"
                        + ":ac_perrec,:ac_medpag,:ac_estado,:ac_datadi,:ac_coddet,:ac_icbpmn,:ac_icbpme,:ac_irlqmn,:ac_irlqme)}", nativeQuery = true)

        @Transactional
        @Modifying
        void swActRecCmp(
                        @Param("opcion") int opcion,
                        @Param("cia") String cia,
                        @Param("ejercicio") String ejercicio,
                        @Param("PER") String PER,
                        @Param("SD") String SD,
                        @Param("ASIENTO") String ASIENTO,
                        @Param("ac_codper") String ac_codper,
                        @Param("ac_subdia") String ac_subdia,
                        @Param("ac_compro") String ac_compro,
                        @Param("ac_feccom") LocalDate ac_feccom,
                        @Param("ac_fecdoc") LocalDate ac_fecdoc,
                        @Param("ac_fecven") LocalDate ac_fecven,
                        @Param("ac_tipdoc") String ac_tipdoc,
                        @Param("ac_docser") String ac_docser,
                        @Param("ac_docnum") String ac_docnum,
                        @Param("ac_numdoc") String ac_numdoc,
                        @Param("ac_tipane") String ac_tipane,
                        @Param("ac_codane") String ac_codane,
                        @Param("ac_tipide") String ac_tipide,
                        @Param("ac_numide") String ac_numide,
                        @Param("ac_nomane") String ac_nomane,
                        @Param("ac_codmon") String ac_codmon,
                        @Param("ac_afemn") Double ac_afemn,
                        @Param("ac_inamn") Double ac_inamn,
                        @Param("ac_igvmn") Double ac_igvmn,
                        @Param("ac_importmn") Double ac_importmn,
                        @Param("ac_iscmn") Double ac_iscmn,
                        @Param("ac_otrmn") Double ac_otrmn,
                        @Param("ac_idemn") Double ac_idemn,
                        @Param("ac_afeme") Double ac_afeme,
                        @Param("ac_iname") Double ac_iname,
                        @Param("ac_igvme") Double ac_igvme,
                        @Param("ac_importme") Double ac_importme,
                        @Param("ac_iscme") Double ac_iscme,
                        @Param("ac_otrme") Double ac_otrme,
                        @Param("ac_ideme") Double ac_ideme,
                        @Param("ac_numdet") String ac_numdet,
                        @Param("ac_fecdet") LocalDate ac_fecdet,
                        @Param("ac_tipcamb") Double ac_tipcamb,
                        @Param("ac_fecdocref") LocalDate ac_fecdocref,
                        @Param("ac_tipdocref") String ac_tipdocref,
                        @Param("ac_docserref") String ac_docserref,
                        @Param("ac_docnumref") String ac_docnumref,
                        @Param("ac_feccrea") LocalDate ac_feccrea,
                        @Param("ac_hracrea") LocalTime ac_hracrea,
                        @Param("ac_usrcrea") String ac_usrcrea,
                        @Param("ac_fecact") LocalDate ac_fecact,
                        @Param("ac_hraact") LocalTime ac_hraact,
                        @Param("ac_usract") String ac_usract,
                        @Param("ac_recmn") Double ac_recmn,
                        @Param("ac_recme") Double ac_recme,
                        @Param("ac_codcla") String ac_codcla,
                        @Param("ac_secuen") String ac_secuen,
                        @Param("ac_cuenta") String ac_cuenta,
                        @Param("ac_perrec") String ac_perrec,
                        @Param("ac_medpag") String ac_medpag,
                        @Param("ac_estado") String ac_estado,
                        @Param("ac_datadi") String ac_datadi,
                        @Param("ac_coddet") String ac_coddet,
                        @Param("ac_icbpmn") Double ac_icbpmn,
                        @Param("ac_icbpme") Double ac_icbpme,
                        @Param("ac_irlqmn") Double ac_irlqmn,
                        @Param("ac_irlqme") Double ac_irlqme);

        @Query(value = "{call SP_Regis_Adi_Compra(:opcion,:cia,:ejercicio,:PER,:SD,:ASIENTO,:ac_codper,:ac_subdia,:ac_compro,:ac_feccom,:ac_fecdoc,:ac_fecven,:ac_tipdoc,:ac_docser,:ac_docnum,"
                        + ":ac_numdoc,:ac_tipane,:ac_codane,:ac_tipide,:ac_numide,:ac_nomane,:ac_codmon,:ac_afemn,:ac_inamn,:ac_igvmn,"
                        + ":ac_importmn,:ac_iscmn,:ac_otrmn,:ac_idemn,:ac_afeme,:ac_iname ,:ac_igvme,:ac_importme,:ac_iscme,:ac_otrme,"
                        + ":ac_ideme,:ac_numdet,:ac_fecdet,:ac_tipcamb,:ac_fecdocref,:ac_tipdocref,:ac_docserref,:ac_docnumref,:ac_feccrea,"
                        + ":ac_hracrea,:ac_usrcrea,:ac_fecact,:ac_hraact,:ac_usract,:ac_recmn,:ac_recme,:ac_codcla,:ac_secuen,:ac_cuenta,"
                        + ":ac_perrec,:ac_medpag,:ac_estado,:ac_datadi,:ac_coddet,:ac_icbpmn,:ac_icbpme,:ac_irlqmn,:ac_irlqme)}", nativeQuery = true)
        List<Map<String, Object[]>> swListarAyuOmi(
                        @Param("opcion") int opcion,
                        @Param("cia") String cia,
                        @Param("ejercicio") String ejercicio,
                        @Param("PER") String PER,
                        @Param("SD") String SD,
                        @Param("ASIENTO") String ASIENTO,
                        @Param("ac_codper") String ac_codper,
                        @Param("ac_subdia") String ac_subdia,
                        @Param("ac_compro") String ac_compro,
                        @Param("ac_feccom") LocalDate ac_feccom,
                        @Param("ac_fecdoc") LocalDate ac_fecdoc,
                        @Param("ac_fecven") LocalDate ac_fecven,
                        @Param("ac_tipdoc") String ac_tipdoc,
                        @Param("ac_docser") String ac_docser,
                        @Param("ac_docnum") String ac_docnum,
                        @Param("ac_numdoc") String ac_numdoc,
                        @Param("ac_tipane") String ac_tipane,
                        @Param("ac_codane") String ac_codane,
                        @Param("ac_tipide") String ac_tipide,
                        @Param("ac_numide") String ac_numide,
                        @Param("ac_nomane") String ac_nomane,
                        @Param("ac_codmon") String ac_codmon,
                        @Param("ac_afemn") Double ac_afemn,
                        @Param("ac_inamn") Double ac_inamn,
                        @Param("ac_igvmn") Double ac_igvmn,
                        @Param("ac_importmn") Double ac_importmn,
                        @Param("ac_iscmn") Double ac_iscmn,
                        @Param("ac_otrmn") Double ac_otrmn,
                        @Param("ac_idemn") Double ac_idemn,
                        @Param("ac_afeme") Double ac_afeme,
                        @Param("ac_iname") Double ac_iname,
                        @Param("ac_igvme") Double ac_igvme,
                        @Param("ac_importme") Double ac_importme,
                        @Param("ac_iscme") Double ac_iscme,
                        @Param("ac_otrme") Double ac_otrme,
                        @Param("ac_ideme") Double ac_ideme,
                        @Param("ac_numdet") String ac_numdet,
                        @Param("ac_fecdet") LocalDate ac_fecdet,
                        @Param("ac_tipcamb") Double ac_tipcamb,
                        @Param("ac_fecdocref") LocalDate ac_fecdocref,
                        @Param("ac_tipdocref") String ac_tipdocref,
                        @Param("ac_docserref") String ac_docserref,
                        @Param("ac_docnumref") String ac_docnumref,
                        @Param("ac_feccrea") LocalDate ac_feccrea,
                        @Param("ac_hracrea") LocalTime ac_hracrea,
                        @Param("ac_usrcrea") String ac_usrcrea,
                        @Param("ac_fecact") LocalDate ac_fecact,
                        @Param("ac_hraact") LocalTime ac_hraact,
                        @Param("ac_usract") String ac_usract,
                        @Param("ac_recmn") Double ac_recmn,
                        @Param("ac_recme") Double ac_recme,
                        @Param("ac_codcla") String ac_codcla,
                        @Param("ac_secuen") String ac_secuen,
                        @Param("ac_cuenta") String ac_cuenta,
                        @Param("ac_perrec") String ac_perrec,
                        @Param("ac_medpag") String ac_medpag,
                        @Param("ac_estado") String ac_estado,
                        @Param("ac_datadi") String ac_datadi,
                        @Param("ac_coddet") String ac_coddet,
                        @Param("ac_icbpmn") Double ac_icbpmn,
                        @Param("ac_icbpme") Double ac_icbpme,
                        @Param("ac_irlqmn") Double ac_irlqmn,
                        @Param("ac_irlqme") Double ac_irlqme);


}
